In [1]:
# Import required libraries and set up our environment
import pandas as pd
from pprint import PrettyPrinter

import boto3
import time

In [2]:

print("📚 Setting up the environment...")
pp = PrettyPrinter(indent=2)
translate = boto3.client("translate")
print("✅ Environment setup complete!")
print(f"🌍 Using AWS region: {translate.meta.region_name}")
print("✅ AWS Translate client ready")

📚 Setting up the environment...
✅ Environment setup complete!
🌍 Using AWS region: eu-west-1
✅ AWS Translate client ready

In [9]:
# Load the dataset

print("📄 Loading articles.csv...")

df = pd.read_csv("articles.csv")

print("✅ Dataset loaded")
print("Columns:", list(df.columns))
print("Language counts:")
print(df["language"].value_counts())

📄 Loading articles.csv...
✅ Dataset loaded
Columns: ['source', 'language', 'url', 'article_text']
Language counts:
language
en    18
bn    12
Name: count, dtype: int64

In [10]:
df

,source,language,url,article_text
0,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,The interim government's revised election time...
1,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,BNP has announced its candidates for 36 more c...
2,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,Discontent runs deep among BNP's partners as t...
3,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,Even though a week has passed since the announ...
4,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,The next national election will be tough for t...
5,The Daily Star,en,https://www.thedailystar.net/opinion/views/new...,"An opinion piece titled ""BNP's notes of dissen..."
6,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,The BNP has survived Sheikh Hasina's 15-year r...
7,The Daily Star,en,https://www.thedailystar.net/opinion/views/new...,The former Prime Minister Khaleda Zia on Tuesd...
8,The Daily Star,en,https://www.thedailystar.net/opinion/editorial...,After having weathered a difficult 15 years in...
9,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,The BNP has alerted its election candidates th...
10,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,The BNP’s earlier thinking on forming an allia...
11,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/9pkzu86yuv,Citing security concerns amid the recent situa...
12,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,The 29 parties allied with the BNP in the simu...
13,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/jsto3ql5zk,Most people in the country believe the Banglad...
14,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,A month after announcing party candidates for ...
15,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,"In the chilly winter weather, electioneering h..."
16,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,Bangladesh Nationalist Party (BNP) Secretary G...
17,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,Bangladesh Nationalist Party (BNP) wants to ma...
18,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,The Bangladesh Nationalist Party (BNP) has fou...
19,Prothom Alo,en,https://en.prothomalo.com/opinion/op-ed/pmyhye...,"""Election"" is the key word of present times, w..."
20,Prothom Alo,en,https://www.prothomalo.com/politics/juller8ad4,ত্রয়োদশ জাতীয় সংসদ নির্বাচন সামনে রেখে সিরাজগঞ...
21,Prothom Alo,bn,https://www.prothomalo.com/bangladesh/district...,লক্ষ্মীপুরে দরজায় তালা লাগিয়ে ও পেট্রল ঢেলে বে...
22,Prothom Alo,en,https://www.prothomalo.com/politics/hpuqtw02xd,অন্তর্বর্তী সরকারের অধীনে অবাধ ও নিরপেক্ষ জাতী...
23,Prothom Alo,en,https://www.prothomalo.com/politics/an2qglrigg,বিএনপির ভারপ্রাপ্ত চেয়ারম্যান তারেক রহমানের প্...
24,Prothom Alo,bn,https://www.prothomalo.com/bangladesh/district...,‘নিরাপত্তা ইস্যুর’ কথা বলে নির্বাচন থেকে সরে দ...
25,Prothom Alo,en,https://www.prothomalo.com/politics/sulmb2nbnt,"প্রতিটি আসনে নির্বাচনী এজেন্ট, পোলিং এজেন্ট ও ..."
26,Prothom Alo,bn,https://www.prothomalo.com/bangladesh/district...,ত্রয়োদশ জাতীয় সংসদ নির্বাচনে চট্টগ্রামের বিভিন...
27,Prothom Alo,en,https://www.prothomalo.com/politics/fshzbhqbdx,আগামী জাতীয় সংসদ নির্বাচনে ২৩৭ আসনে প্রার্থী ঘ...
28,Prothom Alo,en,https://www.prothomalo.com/opinion/column/0ziw...,আওয়ামী লীগ সরকারের আমলে একটি কবিতার পঙ্‌ক্তি ব...
29,Prothom Alo,en,https://www.prothomalo.com/opinion/column/nkxg...,বাংলাদেশ রাজনৈতিকভাবে এতটা বিভক্ত যে কোনো দুজন...

In [5]:
def translate_to_en(text, source_lang):
    """
    Translate text to English using Amazon Translate.
    Safely handles empty or NaN values.
    """
    if text is None or (isinstance(text, float) and pd.isna(text)) or str(text).strip() == "":
        return None

    response = translate.translate_text(
        Text=str(text)[:5000],            # AWS limit
        SourceLanguageCode=source_lang,
        TargetLanguageCode="en"
    )

    return response["TranslatedText"]

In [6]:
def translate_non_english_rows(
    df,
    text_col="article_text",
    lang_col="language",
    sleep_s=0.1
):
    df = df.copy()

    # Ensure bookkeeping columns exist
    if "text_orig_ln" not in df.columns:
        df["text_orig_ln"] = pd.NA
    if "translated_text" not in df.columns:
        df["translated_text"] = pd.NA
    if "translate_error" not in df.columns:
        df["translate_error"] = pd.NA

    # Mask for non-English rows
    mask = (
        df[lang_col].notna()
        & (df[lang_col].str.lower() != "en")
        & df[text_col].notna()
    )

    # Freeze original non-English text
    df.loc[mask, "text_orig_ln"] = df.loc[mask, text_col]

    print("🔁 Translating non-English articles...")

    for idx, row in df.loc[mask, [text_col, lang_col]].iterrows():
        try:
            df.at[idx, "translated_text"] = translate_to_en(
                row[text_col],
                row[lang_col].lower()
            )
            print(f"✅ Translated row {idx}")

        except Exception as e:
            df.at[idx, "translate_error"] = str(e)
            print(f"❌ Translation failed at row {idx}: {str(e)}")

        if sleep_s:
            time.sleep(sleep_s)

    # English rows → copy text directly
    en_mask = df[lang_col].str.lower() == "en"
    df.loc[en_mask, "translated_text"] = df.loc[en_mask, text_col]

    return df

In [7]:
translated_df = translate_non_english_rows(
    df,
    text_col="article_text",
    lang_col="language",
    sleep_s=0.1
)

🔁 Translating non-English articles...
✅ Translated row 10
✅ Translated row 11
✅ Translated row 12
✅ Translated row 13
✅ Translated row 14
✅ Translated row 15
✅ Translated row 16
✅ Translated row 17
✅ Translated row 18
✅ Translated row 21
✅ Translated row 24
✅ Translated row 26

In [14]:
translated_df

,source,language,url,article_text,text_orig_ln,translated_text,translate_error
0,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,The interim government's revised election time...,<NA>,The interim government's revised election time...,<NA>
1,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,BNP has announced its candidates for 36 more c...,<NA>,BNP has announced its candidates for 36 more c...,<NA>
2,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,Discontent runs deep among BNP's partners as t...,<NA>,Discontent runs deep among BNP's partners as t...,<NA>
3,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,Even though a week has passed since the announ...,<NA>,Even though a week has passed since the announ...,<NA>
4,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,The next national election will be tough for t...,<NA>,The next national election will be tough for t...,<NA>
5,The Daily Star,en,https://www.thedailystar.net/opinion/views/new...,"An opinion piece titled ""BNP's notes of dissen...",<NA>,"An opinion piece titled ""BNP's notes of dissen...",<NA>
6,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,The BNP has survived Sheikh Hasina's 15-year r...,<NA>,The BNP has survived Sheikh Hasina's 15-year r...,<NA>
7,The Daily Star,en,https://www.thedailystar.net/opinion/views/new...,The former Prime Minister Khaleda Zia on Tuesd...,<NA>,The former Prime Minister Khaleda Zia on Tuesd...,<NA>
8,The Daily Star,en,https://www.thedailystar.net/opinion/editorial...,After having weathered a difficult 15 years in...,<NA>,After having weathered a difficult 15 years in...,<NA>
9,The Daily Star,en,https://www.thedailystar.net/news/bangladesh/p...,The BNP has alerted its election candidates th...,<NA>,The BNP has alerted its election candidates th...,<NA>
10,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,The BNP’s earlier thinking on forming an allia...,The BNP’s earlier thinking on forming an allia...,A BNP a. Relevant responsible sources say the ...,<NA>
11,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/9pkzu86yuv,Citing security concerns amid the recent situa...,Citing security concerns amid the recent situa...,Citing security concerns amid the recent situa...,<NA>
12,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,The 29 parties allied with the BNP in the simu...,The 29 parties allied with the BNP in the simu...,The 29 parties allied with the BNP in the simu...,<NA>
13,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/jsto3ql5zk,Most people in the country believe the Banglad...,Most people in the country believe the Banglad...,Most people in the country believe the Banglad...,<NA>
14,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,A month after announcing party candidates for ...,A month after announcing party candidates for ...,A month after announcing party candidates for ...,<NA>
15,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,"In the chilly winter weather, electioneering h...","In the chilly winter weather, electioneering h...","In the chilly winter weather, elections have g...",<NA>
16,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,Bangladesh Nationalist Party (BNP) Secretary G...,Bangladesh Nationalist Party (BNP) Secretary G...,Segretario Generale Mirza Fakhrul Islam Alamgi...,<NA>
17,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,Bangladesh Nationalist Party (BNP) wants to ma...,Bangladesh Nationalist Party (BNP) wants to ma...,The Bangladesh Nationalist Party (BNP) wants t...,<NA>
18,Prothom Alo,bn,https://en.prothomalo.com/bangladesh/politics/...,The Bangladesh Nationalist Party (BNP) has fou...,The Bangladesh Nationalist Party (BNP) has fou...,The Bangladesh Nationalist Party (BNP) has fou...,<NA>
19,Prothom Alo,en,https://en.prothomalo.com/opinion/op-ed/pmyhye...,"""Election"" is the key word of present times, w...",<NA>,"""Election"" is the key word of present times, w...",<NA>
20,Prothom Alo,en,https://www.prothomalo.com/politics/juller8ad4,ত্রয়োদশ জাতীয় সংসদ নির্বাচন সামনে রেখে সিরাজগঞ...,<NA>,ত্রয়োদশ জাতীয় সংসদ নির্বাচন সামনে রেখে সিরাজগঞ...,<NA>
21,Prothom Alo,bn,https://www.prothomalo.com/bangladesh/district...,লক্ষ্মীপুরে দরজায় তালা লাগিয়ে ও পেট্রল ঢেলে বে...,লক্ষ্মীপুরে দরজায় তালা লাগিয়ে ও পেট্রল ঢেলে বে...,"In Lakshmipur, a BNP leader named Belal Hossai...",<NA>
22,Prothom Alo,en,https://www.prothomalo.com/politics/hpuqtw02xd,অন্তর্বর্তী সরকারের অধীনে অবাধ ও নিরপেক্ষ জাতী...,<NA>,অন্তর্বর্তী সরকারের অধীনে অবাধ ও নিরপেক্ষ জাতী...,<NA>
23,Prothom Alo,en,https://www.prothomalo.com/politics/an2qglrigg,বিএনপির ভারপ্রাপ্ত চেয়ারম্যান তারেক রহমানের প্...,<NA>,বিএনপির ভারপ্রাপ্ত চেয়ারম্যান তারেক রহমানের প্...,<NA>
24,Prothom Alo,bn,https://www.prothomalo.com/bangladesh/district...,‘নিরাপত্তা ইস্যুর’ কথা বলে নির্বাচন থেকে সরে দ...,‘নিরাপত্তা ইস্যুর’ কথা বলে নির্বাচন থেকে সরে দ...,"In Narayanganj-5 (city-port) seat, BNP-nominat...",<NA>
25,Prothom Alo,en,https://www.prothomalo.com/politics/sulmb2nbnt,"প্রতিটি আসনে নির্বাচনী এজেন্ট, পোলিং এজেন্ট ও ...",<NA>,"প্রতিটি আসনে নির্বাচনী এজেন্ট, পোলিং এজেন্ট ও ...",<NA>
26,Prothom Alo,bn,https://www.prothomalo.com/bangladesh/district...,ত্রয়োদশ জাতীয় সংসদ নির্বাচনে চট্টগ্রামের বিভিন...,ত্রয়োদশ জাতীয় সংসদ নির্বাচনে চট্টগ্রামের বিভিন...,Candidates have started collecting nominations...,<NA>
27,Prothom Alo,en,https://www.prothomalo.com/politics/fshzbhqbdx,আগামী জাতীয় সংসদ নির্বাচনে ২৩৭ আসনে প্রার্থী ঘ...,<NA>,আগামী জাতীয় সংসদ নির্বাচনে ২৩৭ আসনে প্রার্থী ঘ...,<NA>
28,Prothom Alo,en,https://www.prothomalo.com/opinion/column/0ziw...,আওয়ামী লীগ সরকারের আমলে একটি কবিতার পঙ্‌ক্তি ব...,<NA>,আওয়ামী লীগ সরকারের আমলে একটি কবিতার পঙ্‌ক্তি ব...,<NA>
29,Prothom Alo,en,https://www.prothomalo.com/opinion/column/nkxg...,বাংলাদেশ রাজনৈতিকভাবে এতটা বিভক্ত যে কোনো দুজন...,<NA>,বাংলাদেশ রাজনৈতিকভাবে এতটা বিভক্ত যে কোনো দুজন...,<NA>

In [12]:
import pandas as pd
import sys

# Assuming you have your dataframe loaded
df = pd.read_csv("articles.csv")

def translate_logic(row):
    text = row['article_text']
    lang = row['language']
    
    # 1. If English, return as is
    if lang == "en":
        return text
    
    # 2. If Bengali, check size for translation
    if lang == "bn":
        byte_size = len(text.encode('utf-8'))
        
        if byte_size <= 10000:
            # Small enough for a single call
            resp = translate.translate_text(Text=text, SourceLanguageCode="bn", TargetLanguageCode="en")
            return resp['TranslatedText']
        
        else:
            # Logic for long articles: Split into chunks
            chunk_size = 3000
            chunks = [
                text[0:chunk_size],
                text[chunk_size:chunk_size*2],
                text[chunk_size*2:chunk_size*3],
                text[chunk_size*3:]
            ]
            
            translated_parts = []
            for chunk in chunks:
                if chunk.strip():
                    resp = translate.translate_text(
                        Text=chunk, 
                        SourceLanguageCode="bn", 
                        TargetLanguageCode="en"
                    )
                    translated_parts.append(resp['TranslatedText'])
            
            return "\n".join(translated_parts)
            
    return text  # Fallback for any other languages

# Apply the function to create the new column
print("🔄 Translating articles...")
df['translated_text'] = df.apply(translate_logic, axis=1)

# Save back to CSV
df.to_csv("articles_updated.csv", index=False)
print("✅ Translation complete and saved!")

🔄 Translating articles...
✅ Translation complete and saved!

In [13]:
len(df["translated_text"])

30

In [16]:
article_list = pd.read_csv("article_list.csv")
article_list["translated_text"] = df["translated_text"]

In [ ]:
article_list.iloc

,Channels,News Title,News url,Language,Sentiment,translated_text
0,The Daily Star,New Polls Timing BNP upbeat process irks Jamaa...,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,The interim government's revised election time...
1,The Daily Star,BNP announces candidates for 36 more constitue...,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,BNP has announced its candidates for 36 more c...
2,The Daily Star,Seat-sharing snub riles BNP allies,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,Discontent runs deep among BNP's partners as t...
3,The Daily Star,Seat sharing BNP still keeps allies hanging,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,Even though a week has passed since the announ...
4,The Daily Star,"Election to be tough for BNP, bigger test if v...",https://www.thedailystar.net/news/bangladesh/p...,en,NaN,The next national election will be tough for t...
5,The Daily Star,Old habits die hard? BNP’s response,https://www.thedailystar.net/opinion/views/new...,en,NaN,"An opinion piece titled ""BNP's notes of dissen..."
6,The Daily Star,BNP at 47: Caught between prospects and perils,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,The BNP has survived Sheikh Hasina's 15-year r...
7,The Daily Star,BNP’s show of force on Airport Road and a poli...,https://www.thedailystar.net/opinion/views/new...,en,NaN,The former Prime Minister Khaleda Zia on Tuesd...
8,The Daily Star,Fulfilling Uprising's Aspirations: Correction ...,https://www.thedailystar.net/opinion/editorial...,en,NaN,After having weathered a difficult 15 years in...
9,Prothom Alo,BNP rethinks its approach to allies,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,The BNP has alerted its election candidates th...
10,Prothom Alo,BNP’s Masuduzzaman quits race over 'security i...,https://en.prothomalo.com/bangladesh/9pkzu86yuv,en,NaN,A BNP a. Relevant responsible sources say the ...
11,Prothom Alo,"Meeting of 29 party allies, decision to sort t...",https://en.prothomalo.com/bangladesh/politics/...,en,NaN,Citing security concerns amid the recent situa...
12,Prothom Alo,66pc say BNP will win the most seats in the el...,https://en.prothomalo.com/bangladesh/jsto3ql5zk,en,NaN,The 29 parties allied with the BNP in the simu...
13,Prothom Alo,BNP wants to push ahead with election plans am...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,Most people in the country believe the Banglad...
14,Prothom Alo,"Candidates busy in campaign, but Reza Kibria d...",https://en.prothomalo.com/bangladesh/politics/...,en,NaN,A month after announcing party candidates for ...
15,Prothom Alo,Those who seek to exploit crisis are enemies o...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,"In the chilly winter weather, elections have g..."
16,Prothom Alo,BNP wants to make Tarique Rahman’s return “mem...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,Segretario Generale Mirza Fakhrul Islam Alamgi...
17,Prothom Alo,BNP in dilemma over implementation of reform r...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,The Bangladesh Nationalist Party (BNP) wants t...
18,Prothom Alo,Is BNP stepping into trouble?,https://en.prothomalo.com/opinion/op-ed/pmyhye...,en,NaN,The Bangladesh Nationalist Party (BNP) has fou...
19,প্রথম আলো,বিএনপি ছেড়ে এনসিপির প্রার্থী হয়ে আলোচনায় সা...,https://www.prothomalo.com/politics/juller8ad4,bn,NaN,"""Election"" is the key word of present times, w..."
20,প্রথম আলো,"‘দরজায় তালা লাগিয়ে’ বিএনপি নেতার ঘরে আগুন, ঘ...",https://www.prothomalo.com/bangladesh/district...,bn,NaN,ত্রয়োদশ জাতীয় সংসদ নির্বাচন সামনে রেখে সিরাজগঞ...
21,প্রথম আলো,সরকারের মান-অভিমানের সুযোগ নেই: তারেক রহমান,https://www.prothomalo.com/politics/hpuqtw02xd,bn,NaN,"In Lakshmipur, a BNP leader named Belal Hossai..."
22,প্রথম আলো,"তারেক রহমানের প্রত্যাবর্তন, সাতটি ট্রেন ভাড়া ...",https://www.prothomalo.com/politics/an2qglrigg,bn,NaN,অন্তর্বর্তী সরকারের অধীনে অবাধ ও নিরপেক্ষ জাতী...
23,প্রথম আলো,নারায়ণগঞ্জে সরে দাঁড়ানো বিএনপি প্রার্থী মাসু...,https://www.prothomalo.com/bangladesh/district...,bn,NaN,বিএনপির ভারপ্রাপ্ত চেয়ারম্যান তারেক রহমানের প্...
24,প্রথম আলো,ভোটের প্রচারকৌশল ও ভোট নিয়ে প্রশিক্ষণের বড় ক...,https://www.prothomalo.com/politics/sulmb2nbnt,bn,NaN,"In Narayanganj-5 (city-port) seat, BNP-nominat..."
25,প্রথম আলো,চট্টগ্রামে এক আসনে মনোনয়নপত্র নিলেন বিএনপির ত...,https://www.prothomalo.com/bangladesh/district...,bn,NaN,"প্রতিটি আসনে নির্বাচনী এজেন্ট, পোলিং এজেন্ট ও ..."
26,প্রথম আলো,"কোন আসনে বিএনপির প্রার্থী কে, দেখে নিন",https://www.prothomalo.com/politics/fshzbhqbdx,bn,NaN,Candidates have started collecting nominations...
27,প্রথম আলো,এক কোটি ‘সৎ মানুষের’ খোঁজ পাবে কি বিএনপি,https://www.prothomalo.com/opinion/column/0ziw...,bn,NaN,আগামী জাতীয় সংসদ নির্বাচনে ২৩৭ আসনে প্রার্থী ঘ...
28,প্রথম আলো,কার ওপর ভরসা করছে বিএনপি,https://www.prothomalo.com/opinion/column/nkxg...,bn,NaN,আওয়ামী লীগ সরকারের আমলে একটি কবিতার পঙ্‌ক্তি ব...